const API = window.RESUME_API_URL || 'http://127.0.0.1:8000';
const state = { token: localStorage.getItem('resume_token'), user: JSON.parse(localStorage.getItem('resume_user') || 'null') };
const $ = (selector) => document.querySelector(selector);

function show(view) { document.querySelectorAll('.view').forEach((item) => item.classList.add('hidden')); $(`#${view}`).classList.remove('hidden'); window.scrollTo(0, 0); if (view === 'history') loadHistory(); }

document.addEventListener('click', (event) => { const button = event.target.closest('[data-view]'); if (button) show(button.dataset.view); });
$('#auth-button').addEventListener('click', () => show(state.token ? 'analyze' : 'login'));
$('#resume-file').addEventListener('change', (event) => { $('#file-name').textContent = event.target.files[0]?.name || 'or click to browse'; });

function setSession(data) { state.token = data.token; state.user = data.user; localStorage.setItem('resume_token', state.token); localStorage.setItem('resume_user', JSON.stringify(state.user)); $('#auth-button').textContent = 'Analyzer'; show('analyze'); }
async function formRequest(path, form) { const response = await fetch(`${API}${path}`, { method: 'POST', body: new FormData(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Request failed'); return data; }

$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); $('#login-error').textContent = ''; try { setSession(await formRequest('/api/auth/login', event.target)); } catch (error) { $('#login-error').textContent = error.message; } });
$('#signup-form').addEventListener('submit', async (event) => { event.preventDefault(); $('#signup-error').textContent = ''; try { setSession(await formRequest('/api/auth/signup', event.target)); } catch (error) { $('#signup-error').textContent = error.message; } });

$('#analyzer-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.target; const error = $('#form-error'); const submit = $('#submit-label'); error.textContent = ''; submit.textContent = 'Analyzing...'; try { const response = await fetch(`${API}/api/analyzer`, { method: 'POST', body: new FormData(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Analysis failed'); renderResult(data); } catch (caught) { error.textContent = caught.message; } finally { submit.textContent = 'Analyze resume'; } });

function list(items) { return (items || []).map((item) => `<li>${escapeHtml(item)}</li>`).join(''); }
function escapeHtml(value) { return String(value).replace(/[&<>\"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', "'": '&#039;' }[character])); }
function renderResult(data) { const result = data.analysis; $('#result-empty').classList.add('hidden'); $('#result').classList.remove('hidden'); $('#result').innerHTML = `<div class="result-card"><h3>${escapeHtml(data.resumeLabel)}</h3><div class="score-row"><span class="big-score">${result.overallScore}<small>/10</small></span><span class="score-label">OVERALL RESUME<br>QUALITY</span>${result.atsMatchScore ? `<span class="score-label">ATS MATCH<br><b>${result.atsMatchScore}/10</b></span>` : ''}</div><p class="summary">${escapeHtml(result.summary)}</p><div class="result-grid"><div class="result-block"><h4>Strengths</h4><ul>${list(result.strengths)}</ul></div><div class="result-block warn"><h4>Focus next</h4><ul>${list(result.weaknesses)}</ul></div><div class="result-block"><h4>Matched keywords</h4><ul>${list(result.matchedKeywords)}</ul></div><div class="result-block warn"><h4>Missing keywords</h4><ul>${list(result.missingKeywords)}</ul></div></div><button id="save-result" class="primary full" ${state.token ? '' : 'disabled'}>${state.token ? 'Save this review' : 'Log in to save'} <span>↗</span></button></div>`; const save = $('#save-result'); if (save && state.token) save.addEventListener('click', () => saveAnalysis(data)); }
async function saveAnalysis(data) { const response = await fetch(`${API}/api/analyzer/save`, { method: 'POST', headers: { Authorization: `Bearer ${state.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ resumeText: data.resumeText, jobDescription: data.jobDescription, analysisResult: data.analysis, resumeLabel: data.resumeLabel, jobLabel: data.jobLabel, originalFileName: data.originalFileName }) }); const result = await response.json(); if (!response.ok) throw new Error(result.detail); $('#save-result').textContent = 'Saved'; }
async function loadHistory() { const listElement = $('#history-list'); if (!state.token) { listElement.innerHTML = '<p>Log in to view saved reviews.</p>'; return; } const response = await fetch(`${API}/api/analyzer/history`, { headers: { Authorization: `Bearer ${state.token}` } }); const items = await response.json(); listElement.innerHTML = items.length ? items.map((item) => `<article class="history-item"><div><h3>${escapeHtml(item.resume_label)}</h3><p>${escapeHtml(item.job_label)} · ${new Date(item.created_at).toLocaleDateString()}</p></div><div><strong>${item.analysisResult.overallScore}/10</strong><button class="delete" data-delete="${item.id}">Delete</button></div></article>`).join('') : '<p>No saved reviews yet.</p>'; document.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', async () => { await fetch(`${API}/api/analyzer/${button.dataset.delete}`, { method: 'DELETE', headers: { Authorization: `Bearer ${state.token}` } }); loadHistory(); })); }
show('landing');
